import { Footer } from "@/components/footer";
import "./globals.css";
import { ABeeZee, Arvo, Kanit, Lora, Play } from "next/font/google";
import Head from "next/head";

const lora = Kanit({
    weight: ["400", "600", "700"],
    style: ["normal", "italic"],
    subsets: ["latin"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={lora.className}>
            <body className={`bg-slate-500 min-h-screen`}>
                <div className="">{children}</div>
            </body>
        </html>
    );
}
